// var age = "i am 17 years old";
// alert(age);
// var userVisiting = "you are visited 12 times in this website";
// alert(userVisiting);
// var birthYear = "My birth year is 2004";
// document.write(birthYear);
// var clientOrder = "John Doe order 5 T-shirts on xyz store";
// // document.write(clientOrder);
// var a = +prompt("Enter first number");
// var b = +prompt("Enter sceond number");
// var result = a + b;
// document.write("<h1> The sum of " + a + " & " + b + " is " + result + "</h1>"); 
// var result1 = a - b;
// document.write("<h1> The subtraction of " + a + " & " + b + " is " + result + "</h1>");
// var result3 = a*b;
// document.write("<h1> The multiplication of " + a + " & " + b + " is " + result3 + "</h1>");
//var result4 = a / b;
//document.write("<h1> The division of " + a + " & " + b + " is " + result4 + "</h1>");
// var a = 5;
// document.write("<h1>" + a + "</h1>");
// var a = ++a;
// document.write("<h1>" + a + "</h1>");
// var b = 7;
// var result = a + b;
// document.write("<h1>" + result + "</h1>");
// var b = --b;
// document.write("<h1>" + b + "</h1>");
// var c = 3;
// var result1 = b/c;
// // document.write("<h1>" + result1 + "</h1>");
// var eachTicketCost = 600;
// var ticketQuantity = 5;
// var totalTicketCost = eachTicketCost*ticketQuantity;
// document.write("<h1> The cost of 5 tickets is " + totalTicketCost + "PKR ");
// var table = 5;
// var count = 0;
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table * count + "</h1>");
// var celciusTemperature = 27;
// var fahrenietTemperature = 88;
// var celciusResult = (fahrenietTemperature - 32) * 5/9;
// document.write("<h1> 27 °C is " + fahrenietTemperature + " °F </h1>");
// var fahrenietResult = (celciusTemperature + 32 ) * 9/5;
// document.write("<h1>" + fahrenietTemperature + " °F is " + fahrenietResult + " °C </h1>" );
// var priceOfFirstItem = 650;
// document.write("<h1> Price of first item is " + priceOfFirstItem + "</h1>");
// var priceOfSecondItem = 100;
// document.write("<h1> Price of second item is " + priceOfSecondItem + "</h1>");
// var quantityOfFirstItem = 3;
// document.write("<h1> Quantity of first item is " + quantityOfFirstItem + "</h1>");
// var quantityOfSecondItem = 7;
// document.write("<h1> Quantity of second item is " + quantityOfSecondItem + "</h1>");
// var totalCostOfFirstItem = priceOfFirstItem*quantityOfFirstItem;
// var totalCostOfSecondItem = priceOfSecondItem*quantityOfSecondItem;
// var deliveryCharges = 100;
// var totalCost = totalCostOfFirstItem + totalCostOfSecondItem + deliveryCharges;
// document.write("<h1> Total cost of your order is " + totalCost + "</h1>");
// document.write("<h1> MARK SHEET </h1>");
// document.write("<h1> Total Marks : 550 </h1>");
// document.write("<h1> Obtained Marke : 508 </h1>");
// document.write("<h1> Percentage : " + 508/550 *100 + "</h1>");
// var currentYear = 2022;
// var birthYear = 2004;
// var myAge = currentYear - birthYear;
// document.write("<h1> Current year is 2022:");
// document.write("<h1> Birth year 2004:");
// document.write("<h1> My Age is " + myAge + "</h1>");
// var radius = 20;
// document.write("<h1> Radius of circle is: 20 </h1>");
// var Circumference = 2*3.14*20;
// document.write("<h1> Circumference of circle is: " + Circumference + "</h1>");
// var area = 3.14 * (20*20);
// document.write("<h1> Area of circl is: " + area + "</h1>");
// var a = 10;
// document.write("RESULTS:");
// document.write("<h1> The value a is: 10 </h>");
// a = ++a;
// document.write("<h1> The value of ++a is: 11 </h1>");
// document.write("<h1> Now the value of a is: 11 </h1>");
// a = a++;
// document.write("<h1> The value of a++ is: 11 </h1>");
// document.write("<h1> Now the value of a is: 12 </h1>");
// a = a--;
// document.write("<h1> The value of a-- is: 11 </h1>");
// document.write("<h1> Now the value of a is: 10 </h1>");
// var a = 2;
// var b = 1;
// var result = --a - --b + ++b + b--;
// document.write("<h1> The value of --a is: 1");
// document.write("<h1> The value of --a - --b is: 1");
// document.write("<h1> The value of --a - --b + ++b is: 1");
// document.write("<h1> The value of --a - --b + ++b + b is: 1");
// var userName = prompt("Enter your name");
// alert("Welcome to " + userName);
// var table = +prompt("Enter the number",5);
// var count = 0;
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// document.write("<h1>" + table + " ✕ " + ++count + " = " + table*count);
// var english = +prompt("Enter your English MArks");
// var math = +prompt("Enter your MAth Marks");
// var physics = +prompt("Enter your Physics Marks");
// var totalMarks = 100;
// document.write("<b> Subject  </b>");
// document.write("<b> Total Marks  </b>");
// document.write("<b> Obtained Marks  </b>");
// document.write("<b> Percentage   </b> <br>");
// document.write("<b> English </b>");
// document.write("<b> Math </b>");
// document.write("<b> Physics </b> <br>");
// document.write("<b> 100 </b>");
// document.write("<b> 100 </b>");
// document.write("<b> 100 </b> <br>");





